# -*- mode: ruby; -*-

Vagrant.configure("2") do |config|
  config.vm.guest = :freebsd
  config.vm.box = "devbox-freebsd"

  config.ssh.shell = "/bin/sh"
  config.ssh.insert_key = false

  config.vm.network :private_network, ip: "172.17.8.11"

  config.vm.synced_folder ".", "/vagrant", :nfs => true

  config.vm.provider :virtualbox do |vb|
    vb.gui = true

    vb.customize ["modifyvm", :id, "--cpus", "3"]
    vb.customize ["modifyvm", :id, "--memory", "4096"]
    vb.customize ["modifyvm", :id, "--vram", "256"]
    vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  config.vm.provision :shell, path: "scripts/prepare.sh"

  config.vm.provision :file, source: "files", destination: "/tmp/"
  config.vm.provision :shell, path: "../../scripts/apply_files.sh"
  config.vm.provision :shell, path: "scripts/users.sh"
  config.vm.provision :shell, path: "scripts/packages.sh"
  config.vm.provision :shell, path: "scripts/virtualbox.sh"
end
