---
- include: "{{ playbook_dir }}/shared_tasks/install_dmg.yml"
  args:
    app_name: "Emacs"
    dmg_url: "https://emacsformacosx.com/emacs-builds/Emacs-25.1-1-universal.dmg"
  when: ansible_distribution == "MacOSX"

# MacOSX comes with a default install of emacs, we want to preceed it on the path
# with a wrapper that calls our new version.
- name: Use emacs 25 in the terminal
  copy: >
    src="{{ role_path }}/files/emacs_wrapper.sh"
    dest=/usr/local/bin/emacs
    mode="u=rwx,g=rx,o=rx"
