#!/usr/bin/env bash
set -euo pipefail

if [[ "${1:-}" == "" ]]; then
    echo "No arguments provided. Usage: install-font font-package-name"
    echo
    echo "Valid fonts are any font package available under nixpkgs"
    exit 1
fi;

FONT_PACKAGE_NAME=$1

echo "Installing ${FONT_PACKAGE_NAME}"
FONT_PACKAGE_DIR=$(nix-build --no-out-link '<nixpkgs>' -A "${FONT_PACKAGE_NAME}")

echo "FONT PACKAGGE DIR: ${FONT_PACKAGE_DIR}"

find "${FONT_PACKAGE_DIR}" -type f \( -name "*.ttf" -o -name "*.otf" \) \
     -exec echo "Installing {} to /Library/Fonts" \; \
     -exec cp {} /Library/Fonts/ \;

fc-cache -f -v
