---
- name: Update apt cache if older then 1 day
  apt:
    update_cache: yes
    cache_valid_time: 86400

- name: Enable https based apt sources
  apt: package=apt-transport-https state=present

- name: Add the jessie-backports apt source
  apt_repository: repo='deb http://ftp.debian.org/debian jessie-backports main' state=present
  register: jessie_backports_apt_source

- name: Add the fpcomplete apt key
  apt_key: keyserver='hkp://keyserver.ubuntu.com:80' id=575159689BEFB442 state=present
  register: fpcomplete_apt_key

- name: Add the fpcomplete apt source
  apt_repository: repo='deb http://download.fpcomplete.com/debian jessie main' state=present
  register: fpcomplete_apt_source

- name: Add the sbt debian apt key
  apt_key: >
    keyserver='hkp://keyserver.ubuntu.com:80'
    id=2EE0EA64E40A89B84B2DF73499E82A75642AC823
    state=present
  register: sbt_apt_key

- name: Add the sbt apt repository
  apt_repository: repo='deb https://dl.bintray.com/sbt/debian /' state=present
  register: sbt_apt_source

- name: Add the nodesource apt key
  apt_key: keyserver='hkp://keyserver.ubuntu.com:80' id=68576280 state=present
  register: nodesource_apt_key

- name: Add the nodesource apt repository
  apt_repository: repo='deb https://deb.nodesource.com/node jessie main' state=present
  register: nodesource_apt_source

- name: Update apt cache if apt keys/sources change
  apt:
    update_cache: yes
  when: >
    jessie_backports_apt_source.changed
    or fpcomplete_apt_key.changed
    or fpcomplete_apt_source.changed
    or sbt_apt_key.changed
    or sbt_apt_source.changed
    or nodesource_apt_key.changed
    or nodesource_apt_source.changed
