---
#- name: Check for installed nvm
#  stat: path="{{ user.home }}/.nvm/bin/cs"
#  register: conscript_installed

- name: Install nvm
  git: >
    dest="{{ user.home }}/.nvm"
    repo=https://github.com/creationix/nvm.git
    version=v0.33.2
    force=no
    update=no
  become: yes
  become_user: "{{ user.name }}"

- name: Configure nvm
  blockinfile:
    dest: "{{ user.home }}/.profile"
    state: present
    insertafter: "# ansible: lang/javascript"
    marker: "# {mark} ansible: lang/javascript"
    block: |
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

- name: Install node
  package: pkg=nodejs state=present
  become: yes
  become_user: "{{ system_install_user | default('root') }}"
  register: install_node

- name: Install node packages for spacemacs
  command: npm install -g tern js-beautify eslint babel-eslint eslint-plugin-react
  become: yes
  become_user: "{{ system_install_user | default('root') }}"
  when: install_node.changed

- name: Install other node packages
  command: npm install -g yarn
  become: yes
  become_user: "{{ system_install_user | default('root') }}"
  when: install_node.changed
