#!/usr/bin/env bash

echo "Linking 64-bit opengl to /run/opengl-driver/lib"
mkdir -p /run/opengl-driver/lib
rm -f /run/opengl-driver/lib/*
ln -s \
   /usr/lib/libGL.so* \
   /usr/lib/libGLX.so* \
   /usr/lib/libGLdispatch.so* \
   /usr/lib/libEGL.so* \
   /usr/lib/libEGL_nvidia.so* \
   /usr/lib/libnvidia-* \
   /run/opengl-driver/lib

echo "Linking 32-bit opengl to /run/opengl-driver-32/lib"
mkdir -p /run/opengl-driver-32/lib
rm -f /run/opengl-driver-32/lib/*
ln -s \
   /usr/lib32/lib32GL.so* \
   /usr/lib32/lib32GLX.so* \
   /usr/lib32/lib32GLdispatch.so* \
   /usr/lib32/lib32EGL.so* \
   /usr/lib32/lib32EGL_nvidia.so* \
   /usr/lib32/lib32nvidia-* \
   /run/opengl-driver-32/lib
