---
- name: Check if giter8 is installed
  stat: path="{{ user.home }}/.conscript/bin/g8"
  become: yes
  become_user: "{{ user.name }}"
  register: giter8_installed

- name: Install giter8
  shell: "{{ user.home }}/.conscript/bin/cs foundweekends/giter8"
  become: yes
  become_user: "{{ user.name }}"
  when: not giter8_installed.stat.exists
