---
- name: Install ruby extension dependencies (debian)
  package: package={{ item }} state=present
  with_items:
    - autoconf
    - bison
    - build-essential
    - libssl-dev
    - libyaml-dev
    - libreadline6-dev
    - zlib1g-dev
    - libncurses5-dev
    - libffi-dev
    - libgdbm3
    - libgdbm-dev
  when: ansible_distribution == "Debian"
  become: yes
  become_user: "{{ system_install_user | default('root') }}"

- name: Ensure rbenv is installed
  git: >
    dest="{{ user.home }}/.rbenv"
    repo=https://github.com/rbenv/rbenv.git
    version=v1.0.0
    force=no
    update=no
  become: yes
  become_user: "{{ user.name }}"

- name: Compile rbenv
  shell: src/configure && make -C src
  args:
    chdir: "{{ user.home }}/.rbenv"

- name: Add rbenv configuration to .profile
  blockinfile:
    dest: "{{ user.home }}/.profile"
    state: present
    insertafter: "# ansible: lang/ruby"
    marker: "# {mark} ansible: lang/ruby"
    block: |
      export PATH="$HOME/.rbenv/bin:$PATH"
      export RBENV_ROOT="$HOME/.rbenv"
      eval "$(rbenv init -)"

- name: Ensure ruby-build is installed
  git: >
    dest="{{ user.home }}/.rbenv/plugins/ruby-build"
    repo=https://github.com/rbenv/ruby-build.git
    version=v20160913
    force=no
    update=no
  become: yes
  become_user: "{{ user.name }}"

- name: Install rubies
  command: "{{ user.home }}/.rbenv/bin/rbenv install -k -s {{ item }}"
  environment:
    RUBY_CONFIGURE_OPTS: '--with-readline-dir="/usr/lib/x86_64-linux-gnu/"'
  become: yes
  become_user: "{{ user.name }}"
  with_items:
    - 2.0.0-p353
    - 2.3.1

- name: Install default gems
  shell: >
    {{ user.home }}/.rbenv/bin/rbenv global {{ item }} &&
    {{ user.home }}/.rbenv/shims/gem install --conservative bundler pry pry-doc ruby_parser rubocop pry-byebug &&
    {{ user.home }}/.rbenv/bin/rbenv rehash
  become: yes
  become_user: "{{ user.name }}"
  with_items:
    - 2.0.0-p353
    - 2.3.1

- name: Use 2.3.1 as the global ruby
  command: "{{ user.home }}/.rbenv/bin/rbenv global 2.3.1"
  become: yes
  become_user: "{{ user.name }}"

- include: "{{ playbook_dir }}/shared_tasks/dotfiles.yml"
