---
- name: Ensure git is installed
  package: pkg=git state=present
  become: yes
  become_user: "{{ system_install_user | default('root') }}"

- include: "{{ playbook_dir }}/shared_tasks/dotfiles.yml"

- name: Configure git user name
  git_config: >
    name=user.name
    scope=global
    value={{ user.text_name }}
  become: yes
  become_user: "{{ user.name }}"

- name: Configure git user email
  git_config: >
    name=user.email
    scope=global
    value={{ user.email }}
  become: yes
  become_user: "{{ user.name }}"
