---
- name: Ensure git is installed
  package: pkg=git state=present
  become: yes
  become_user: "{{ system_install_user | default('root') }}"

- include: "{{ playbook_dir }}/shared_tasks/dotfiles.yml"

- name: Configure git user name
  git_config: >
    name=user.name
    scope=global
    value={{ user.text_name }}
  become: yes
  become_user: "{{ user.name }}"

- name: Configure git user email
  git_config: >
    name=user.email
    scope=global
    value={{ user.email }}
  become: yes
  become_user: "{{ user.name }}"

- name: Install git open
  get_url:
    url: https://raw.githubusercontent.com/paulirish/git-open/v1.3.1/git-open
    dest: "{{ user.home }}/.bin/git-open"
    checksum: "sha256:7a4c3a95f7e6b9b89dc40865a6be54e114820a235b5a9e45137603f7643b71d6"
    mode: u=rwx,g=rx,o=rx
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
