#!/usr/bin/env bash

echo "* Installing nvidia drivers"
pacman -S \
  nvidia \
  nvidia-utils \
  lib32-nvidia-utils \
  nvidia-settings

pacman -S \
  vulkan-icd-loader \
  lib32-vulkan-icd-loader

pacman -S \
  steam \
  lutris \
  wine \
  wine-mono \
  wine_gecko

pacman -S \
       ttf-hack \
       ttf-inconsolata \
       cantarell-fonts

pacman -S pinta
