#!/usr/bin/env bash
set -euo pipefail

SOURCE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "Provisioning nixos home configuration."
${SOURCE_DIR}/scripts/install-default-nixpkgs nixpkgs

echo "Provisioning nixos home configuration"
${SOURCE_DIR}/scripts/install-nix-env nixos-dev-env
${SOURCE_DIR}/scripts/sync-spacemacs
${SOURCE_DIR}/scripts/sync-vim
${SOURCE_DIR}/scripts/sync-bash-my-aws

echo "Provisioning dotfiles"
${SOURCE_DIR}/scripts/link-dotfiles common
${SOURCE_DIR}/scripts/link-dotfiles linux

echo "Provisioning private files"
${SOURCE_DIR}/scripts/sync-private

echo "Provisioning complete."
