#!/usr/bin/env bash
set -euo pipefail

SOURCE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
NIXOS_CONFIG_DIR="${SOURCE_DIR}/../nixos"

if [[ "${1:-}" == "" ]]; then
    echo "No nixos configuration selected. Usage: install-nixos-system configuration"
    echo
    echo "Valid configurations are:"
    echo
    find "${NIXOS_CONFIG_DIR}" -mindepth 1 -maxdepth 1 -type d -printf "- %f\n"
    echo
    exit 1
fi;

NIXOS_CONFIG=$1
NIXOS_CONFIG_PATH="${NIXOS_CONFIG_DIR}/${NIXOS_CONFIG}"

if [[ ! -d "${NIXOS_CONFIG_PATH}" ]]; then
    echo "'${NIXOS_CONFIG_PATH}' is not a valid directory"
    exit 1
fi;

echo "Provisioning nixos system configuration for: ${NIXOS_CONFIG}"

echo "Provisoning local nixpkg forks"
${SOURCE_DIR}/scripts/sync-nixpkgs
${SOURCE_DIR}/scripts/sync-nixpkgs-unstable

echo "Removing existing channels"
nix-channel --remove nixos
nix-channel --remove nixos-unstable

echo "Symlinking nixos configuration"
ln -fs ${NIXOS_CONFIG_PATH}/configuration.nix /etc/nixos/configuration.nix
ln -fs ${NIXOS_CONFIG_PATH}/hardware-configuration.nix /etc/nixos/hardware-configuration.nix

echo "Switching to new system configuration"
nixos-rebuild switch

echo "Provisioning complete."
