#! /usr/bin/env bash
set -euo pipefail

SOURCE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
MACHINE_DIR="${SOURCE_DIR}/../config/machines"

if [[ "${1:-}" == "" ]]; then
  echo "No arguments provided. Usage: install <machine-name>"
  echo
  echo "Valid machines are:"
  echo
  find "${MACHINE_DIR}" -mindepth 1 -maxdepth 1 -type d -exec basename {} \;
  echo
  exit 1
fi;

if [[ $(/usr/bin/env id -u) -ne 0 ]]; then
  echo "This script must be run as root to avoid symlink creation errors from \`nixos-rebuild switch\`"
  exit 1
fi;

MACHINE_NAME=$1

trap "popd > /dev/null" EXIT
pushd $PWD > /dev/null
cd $(dirname "$0")/..

echo "Applying system configuration"
nix-shell --argstr "machine" "${MACHINE_NAME}" --run "nixos-rebuild switch"

echo "Install Complete: after logging in/out or restarting you can run 'nixos-rebuild switch' from anywhere!"
