#!/usr/bin/env bash
set -euo pipefail

SOURCE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "Provisioning osx system configuration."

${SOURCE_DIR}/scripts/sync-nixpkgs-darwin
${SOURCE_DIR}/scripts/sync-nixpkgs-unstable
${SOURCE_DIR}/scripts/osx/use-nix-forks

# Load the nixpath so we can use our nix forks in this script.
source /etc/nixpath

# Font installation under nix isn't as easy for OSX as it is for NixOS so
# we need a few manual steps
echo "Installing Fonts"
${SOURCE_DIR}/scripts/osx/install-font hack-font
