#!/usr/bin/env bash
set -euo pipefail

SOURCE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "Provisioning nixos system configuration."

FORK_NAME="nixpkgs" \
         FORK_REMOTE="origin" \
         FORK_BRANCH="nixos-18.09" \
         ${SOURCE_DIR}/scripts/sync-nixpkgs-fork

FORK_NAME="nixpkgs-unstable" \
         FORK_REMOTE="channels" \
         FORK_BRANCH="nixpkgs-unstable" \
         ${SOURCE_DIR}/scripts/sync-nixpkgs-fork

echo "Removing existing channels"
nix-channel --remove nixos
nix-channel --remove nixos-unstable

echo "Hardlinking OS configuration"
ln -f ${SOURCE_DIR}/../nixos/common.nix /etc/nixos/common.nix
ln -f ${SOURCE_DIR}/../nixos/laptop-metabox.nix /etc/nixos/configuration.nix

echo "Symlinking OS files"
ln -s ${SOURCE_DIR}/../nixos/metabox /etc/nixos/metabox

echo "Giving edit permissions to jake"
chown -R jake: /etc/nixos

echo "Switching to new system configuration"
nixos-rebuild switch

echo "Provisioning complete."
