#!/usr/bin/env bash
set -euo pipefail

SOURCE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "Provisioning nixos system configuration."

echo "Using nixos unstable"
nix-channel --add https://nixos.org/channels/nixos-unstable nixos

echo "Updating OS configuration"
cp ${SOURCE_DIR}/../nixos/common.nix /etc/nixos/common.nix
cp ${SOURCE_DIR}/../nixos/laptop-t420.nix /etc/nixos/configuration.nix

nix-channel --update
nixos-rebuild switch

echo "Provisioning complete."
