#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

PS1='[\u@\h \W]\$ '

# Git aliases
alias gc="git commit"
alias gf="git fetch --all"
alias gs="git status"

# Enable dircolors for bash if it exists
if [ -x "$(command -v foo)" ]; then
    eval $(dircolors -b ${HOME}/.dircolors)
fi;

# Source the bash-my-aws functions
for f in ~/.bash-my-aws/lib/*-functions; do source $f; done

# Enable bash-my-aws auto completion
source ~/.bash-my-aws/bash_completion.sh

# Source any additional bashrc scripts in ~/.bashrc.d
if [[ -d "${HOME}/.bashrc.d" ]]; then
    for script in ${HOME}/.bashrc.d/*.sh ; do
        if [ -r "${script}" ]; then
            source ${script}
        fi
    done
fi;

# Enable direnv
eval "$(direnv hook bash)"
