---
- include: "{{ playbook_dir }}/shared_tasks/os_vars.yml"

# Java is installed by our role dependencies, see java/meta/main.yml
- name: Install jenv
  git: >
    dest="{{ user.home }}/.jenv"
    repo=https://github.com/gcuisinier/jenv.git
    version=0.4.4
    force=no
    update=no
  become: yes
  become_user: "{{ user.name }}"

- name: Add jenv configuration to .profile
  blockinfile:
    dest: "{{ user.home }}/.profile"
    state: present
    insertafter: "# ansible: lang/java"
    marker: "# {mark} ansible: lang/java"
    block: |
      export PATH="$HOME/.jenv/bin:$PATH"
      export JENV_ROOT="$HOME/.jenv"
      eval "$(jenv init -)"

- name: Clear installed javas from jenv
  file: >
    path={{ user.home }}/.jenv/versions
    state=absent

- name: Add installed javas to jenv
  shell: |
    mkdir -p {{ user.home }}/.jenv/versions
    {{ user.home }}/.jenv/bin/jenv add {{ item }}
  become: yes
  become_user: "{{ user.name }}"
  with_items:
    - "{{ java8_131_home_path }}"

- name: Use Java 1.8 globally
  command: "{{ user.home }}/.jenv/bin/jenv global 1.8"
  become: yes
  become_user: "{{ user.name }}"
