#!/usr/bin/env bash
set -euo pipefail

# We need to prefetch our sources since the nix build user doesn't have permission.
echo "Prefetching rea-as"
nix-prefetch-git \
    git@git.realestate.com.au:cowbell/rea-as.git \
    88337bfdf733248b533a945648cb5cbe5a07299e \
    1n8plr45ggyjyv0n509rz59c284hw75nzyf42j5bc2z6lp8gd8ln

echo "Installing rea-as"
nix-env -iA nixpkgs.rea-as

echo "Prefetching aws-console-url"
nix-prefetch-git \
    git@git.realestate.com.au:david-yeung/aws-console-url.git \
    620d18e5989afa9ed3cd4390bd7e441872f49bd6 \
    1vh7c9wfhdc7amvan0wzywdsvqbj8csrpsbiz4r50n7xhv6alh5v

echo "Installing aws-console-url"
nix-env -iA nixpkgs.aws-console-url

echo "Prefetching rea-slip-utils"
nix-prefetch-git \
    git@git.realestate.com.au:cowbell/rea-slip-utils.git \
    v1.1.0 \
    0bdw004w5z6vv53dpms7sv751wj0cg0zga4yisv31l5prlksj4pb

echo "Installing rea-slip-utils"
nix-env -iA nixpkgs.rea-slip-utils

echo "Done."
