#!/usr/bin/env bash
set -euo pipefail

# We need to prefetch our sources since the nix build user doesn't have permission.
echo "Prefetching rea-as"
nix-prefetch-git \
    git@git.realestate.com.au:cowbell/rea-as.git \
    e76e1cbfe7b8010f845e51379d3bbcd889dfe6c8 \
    10ipnni2b68y36bxjnmy8y6jrrm26n1q84kl00pzsb19v4zjn9f7

echo "Installing rea-as"
nix-env -iA nixpkgs.rea-as

echo "Prefetching aws-console-url"
nix-prefetch-git \
    git@git.realestate.com.au:david-yeung/aws-console-url.git \
    620d18e5989afa9ed3cd4390bd7e441872f49bd6 \
    1vh7c9wfhdc7amvan0wzywdsvqbj8csrpsbiz4r50n7xhv6alh5v

echo "Installing aws-console-url"
nix-env -iA nixpkgs.aws-console-url

echo "Done."
