#!/usr/bin/env bash
SOURCE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

SYNC_NAME="aws-shortcuts" \
    SYNC_REPO=git@git.realestate.com.au:resi-lob/aws-shortcuts.git \
    SYNC_REF=c141defe4b565fc280552bc8f6f403d77eeec1c1 \
    SYNC_TARGET_DIR=$HOME/.aws-shortcuts \
    ${SOURCE_DIR}/../sync-git-repo
