---
- name: Ensure the `wheel` group exists
  group: >
    name=wheel
    state=present

- name: Ensure the `wheel` group doesn't require a password for sudo
  lineinfile: >
    dest=/etc/sudoers
    state=present
    regexp='^%wheel'
    line='%wheel ALL=(ALL) NOPASSWD: ALL'

- name: Ensure `{{ user.name }}` exists
  user: >
    name="{{ user.name }}"
    comment="{{ user.text_name }}"
    home="{{ user.home }}"
    shell=/bin/bash
    createhome=yes
    groups=wheel
    state=present

- name: Ensure `{{ user.name }}` doesn't need a password to log in
  command: passwd -d {{ user.name }}
