#!/usr/bin/env bash
set -euo pipefail

SOURCE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [[ "$1" == "" ]]; then
    echo "No arguments provided. Usage: install-nix-env env-name"
    exit 1
fi;

NIX_ENV_NAME=$1

echo "Linking nix config"
rm -rf "${HOME}/.config/nixpkgs"
ln -s "${SOURCE_DIR}/../../nixpkgs" "${HOME}/.config/nixpkgs"

echo "Installing '${NIX_ENV_NAME}' environment to local profile"
nix-env -i ${NIX_ENV_NAME}
echo "Done."
echo
