#!/usr/bin/env bash
set -euo pipefail

SOURCE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
DOTFILES_DIR="${SOURCE_DIR}/../../dotfiles"

if [[ "${1:-}" == "" ]]; then
    echo "No arguments provided. Usage: link-dotfiles dotfile-dir-name"
    echo
    echo "Valid dotfiles are:"
    echo
    find "${DOTFILES_DIR}" -mindepth 1 -maxdepth 1 -type d -exec basename {} \;
    echo
    exit 1
fi;

DOTFILES_DIR_NAME=$1
DOTFILES_PATH="${DOTFILES_DIR}/${DOTFILES_DIR_NAME}"

if [[ ! -d "${DOTFILES_PATH}" ]]; then
    echo "'${DOTFILES_PATH}' is not a valid directory"
    exit 1
fi;


echo "Linking dotfiles from ${DOTFILES_PATH} ..."
/usr/bin/env rcup -- -d "${DOTFILES_PATH}"
