#!/usr/bin/env bash
set -euo pipefail

SOURCE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
DOTFILES_DIR="${SOURCE_DIR}/../../dotfiles"

echo "Linking dotfiles from ${DOTFILES_DIR} ..."
/usr/bin/env rcup -- -d "${DOTFILES_DIR}/common" -d "${DOTFILES_DIR}/linux"
echo "Done."
echo
