#!/usr/bin/env bash
SOURCE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

${SOURCE_DIR}/sync-git-repo \
             --repo https://github.com/VundleVim/Vundle.vim.git \
             --branch master \
             --remote-branch origin/master \
             --ref v0.10.2 \
             --target-dir "$HOME/.vim/bundle/Vundle.vim"

echo "Installing vim plugins"
vim +PluginInstall +qall
