#!/usr/bin/env bash
set -euo pipefail

SOURCE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

print_valid_fork_names() {
    echo "Valid fork names are:"
    echo
    echo "- nixpkgs"
    echo "- nixpkgs-unstable"
    echo "- nixpkgs-darwin"
}

if [[ "${1:-}" == "" ]]; then
    echo "No arguments provided. Usage: sync-nixpkgs fork-name"
    echo
    print_valid_fork_names
    echo
    exit 1
fi;

FORK_NAME=$1

if [ "${FORK_NAME}" == 'nixpkgs' ]; then
    # Last updated: 2019-01-05
    export FORK_REMOTE="channels"
    export FORK_BRANCH="nixos-18.09"
    export FORK_REF="9d608a6f592144b5ec0b486c90abb135a4b265eb"
elif [ "${FORK_NAME}" == 'nixpkgs-unstable' ]; then
    # Last updated: 2019-01-04
    export FORK_REMOTE="channels"
    export FORK_BRANCH="nixpkgs-unstable"
    export FORK_REF="45779f013c885b5c0da6852c0c01ec1c50670c5b"
elif [ "${FORK_NAME}" == 'nixpkgs-darwin' ]; then
    # Last updated: 2019-01-04
    export FORK_REMOTE="channels"
    export FORK_BRANCH="nixpkgs-18.09-darwin"
    export FORK_REF="eb0480ad6c5f414929a85e92b6ebf5401f44e313"
else
    echo "Unknown fork name provided: ${FORK_NAME}"
    print_valid_fork_names
    echo
    exit 1
fi;

FORK_CACHE_DIR="/nix/do-not-touch-base-nixpkgs-cache"
FORK_TARGET_DIR="/nix/${FORK_NAME}"
FORK_REMOTE_BRANCH="${FORK_REMOTE}/${FORK_BRANCH}"

${SOURCE_DIR}/sync-git-repo \
  --repo https://github.com/Vodurden/nixpkgs.git \
  --branch "${FORK_BRANCH}" \
  --remote-branch "${FORK_REMOTE_BRANCH}" \
  --ref "${FORK_REF}" \
  --remote channels git://github.com/NixOS/nixpkgs-channels.git \
  --remote upstream git://github.com/NixOS/nixpkgs.git \
  --cache-dir "${FORK_CACHE_DIR}" \
  --target-dir "${FORK_TARGET_DIR}"
