#!/usr/bin/env bash
set -euo pipefail

SOURCE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

print_valid_fork_names() {
    echo "Valid fork names are:"
    echo
    echo "- nixpkgs"
    echo "- nixpkgs-unstable"
    echo "- nixpkgs-darwin"
}

if [[ "${1:-}" == "" ]]; then
    echo "No arguments provided. Usage: sync-nixpkgs fork-name"
    echo
    print_valid_fork_names
    echo
    exit 1
fi;

FORK_NAME=$1

if [ "${FORK_NAME}" == 'nixpkgs' ]; then
    # Last updated: 2019-03-23
    export FORK_REMOTE="channels"
    export FORK_BRANCH="nixos-18.09"
    export FORK_REF="680f9d7ea90dd0b48b51f29899c3110196b0e913"
elif [ "${FORK_NAME}" == 'nixpkgs-unstable' ]; then
    # Last updated: 2019-03-23
    export FORK_REMOTE="channels"
    export FORK_BRANCH="nixpkgs-unstable"
    export FORK_REF="373488e6f4c3dc3bb51cabcb959e4a70eb5d7b2c"
elif [ "${FORK_NAME}" == 'nixpkgs-darwin' ]; then
    # Last updated: 2019-03-02
    export FORK_REMOTE="channels"
    export FORK_BRANCH="nixpkgs-18.09-darwin"
    export FORK_REF="aabc61049c011b40ef15c354d7d84c840d6b6a6d"
else
    echo "Unknown fork name provided: ${FORK_NAME}"
    print_valid_fork_names
    echo
    exit 1
fi;

FORK_CACHE_DIR="/nix/do-not-touch-base-nixpkgs-cache"
FORK_TARGET_DIR="/nix/${FORK_NAME}"
FORK_REMOTE_BRANCH="${FORK_REMOTE}/${FORK_BRANCH}"

${SOURCE_DIR}/sync-git-repo \
  --repo https://github.com/Vodurden/nixpkgs.git \
  --branch "${FORK_BRANCH}" \
  --remote-branch "${FORK_REMOTE_BRANCH}" \
  --ref "${FORK_REF}" \
  --remote channels git://github.com/NixOS/nixpkgs-channels.git \
  --remote upstream git://github.com/NixOS/nixpkgs.git \
  --cache-dir "${FORK_CACHE_DIR}" \
  --target-dir "${FORK_TARGET_DIR}"
