#!/usr/bin/env bash
SOURCE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

SYNC_NAME="bash-my-aws" \
  SYNC_REPO=https://github.com/realestate-com-au/bash-my-aws.git \
  SYNC_REF=master \
  SYNC_TARGET_DIR=$HOME/.bash-my-aws \
  ${SOURCE_DIR}/sync-git-repo
