#!/usr/bin/env bash
SOURCE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

${SOURCE_DIR}/sync-git-repo \
  --repo https://github.com/syl20bnr/spacemacs.git \
  --branch develop \
  --remote-branch origin/develop \
  --ref 8bbf6b3f5372f55b0fbcb9cc0bf9ea1ce98c77b7 \
  --target-dir "$HOME/.emacs.d"
