#!/usr/bin/env bash
SOURCE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

${SOURCE_DIR}/sync-git-repo \
             --repo https://github.com/bash-my-universe/bash-my-aws.git \
             --branch master \
             --remote-branch origin/master \
             --ref 850109172c0926d387ff64ea3c4e9dec81ed88bd \
             --target-dir "$HOME/.bash-my-aws"
