#!/usr/bin/env bash
set -euo pipefail

SOURCE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

FORK_NAME="nixpkgs-unstable" \
         FORK_REMOTE="channels" \
         FORK_BRANCH="nixpkgs-unstable" \
         ${SOURCE_DIR}/sync-nixpkgs-repo