---
- name: Ensure sbt is installed
  package: package=sbt state=present
  become: yes
  become_user: "{{ system_install_user | default('root') }}"

- name: Install scalastyle
  get_url: >
    url=https://oss.sonatype.org/content/repositories/releases/org/scalastyle/scalastyle_2.11/0.8.0/scalastyle_2.11-0.8.0-batch.jar
    dest=/usr/local/bin/scalastyle_2.11-0.8.0-batch.jar
    checksum=sha1:66ce54a6eb8dde221c6efb530b2c108c876c0e27

- name: Ensure scalastyle command-line wrapper exists
  copy: >
    src="{{ role_path }}/files/scalastyle"
    dest=/usr/local/bin/scalastyle
    mode="u=rwx,g=rx,o=rx"

- include: "{{ playbook_dir }}/shared_tasks/dotfiles.yml"

- name: Enable scala jenv plugins
  shell: eval "$({{ user.home }}/.jenv/bin/jenv init -)" && jenv enable-plugin {{ item }}
  with_items:
    - sbt
    - scala
  become: yes
  become_user: "{{ user.name }}"
