# -*- mode: ruby; -*-

Vagrant.configure("2") do |config|
  config.vm.guest = :freebsd

  config.vm.box = "devbox-freebsd"

  config.ssh.username = "root"
  config.ssh.password = "vagrant"
  config.ssh.shell = "tcsh"

  config.vm.network :private_network, ip: "172.17.8.11"
  config.vm.synced_folder ".", "/vagrant", :nfs => true

  config.vm.provider :virtualbox do |vb|
    vb.gui = true

    vb.customize ["modifyvm", :id, "--cpus", "4"]
    vb.customize ["modifyvm", :id, "--memory", "4096"]
    vb.customize ["modifyvm", :id, "--vram", "256"]
    vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  config.vm.provision :file, source: "files", destination: "/tmp/files"
  config.vm.provision :shell, path: "scripts/apply_files.sh"
  config.vm.provision :shell, path: "scripts/users.sh"
  config.vm.provision :shell, path: "scripts/packages.sh"
end
