# -*- mode: ruby; -*-

Vagrant.configure("2") do |config|
  config.vm.box = "devbox-core"

  config.ssh.insert_key = false

  config.vm.network :private_network, ip: "172.17.8.11"

  config.vm.synced_folder ".", "/vagrant"

  config.vm.provider :virtualbox do |vb|
    vb.gui = true

    vb.customize ["modifyvm", :id, "--cpus", "3"]
    vb.customize ["modifyvm", :id, "--memory", "4096"]
    vb.customize ["modifyvm", :id, "--vram", "256"]
    vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  config.vm.provision :shell, path: "scripts/packages.sh"

  # We want our `.spacemacs` file available when we bootstrap to:
  # * Prevent spacemacs asking for first-time configuration
  # * Preload layers we want to use
  config.vm.provision :file,
    source: "../../files/home/jake/.spacemacs",
    destination: "/tmp/.spacemacs"
  config.vm.provision :shell, path: "scripts/spacemacs.sh"
end
