---
- name: Configure conscript
  blockinfile:
    dest: "{{ user.home }}/.profile"
    state: present
    insertafter: "# ansible: tools/conscript"
    marker: "# {mark} ansible: tools/conscript"
    block: |
      export CONSCRIPT_HOME="$HOME/.conscript"
      export CONSCRIPT_OPTS="-Dfile.encoding=UTF-8"
      export PATH="$CONSCRIPT_HOME/bin:$PATH"

- name: Check for installed conscript
  stat: path="{{ user.home }}/.conscript/bin/cs"
  register: conscript_installed

- name: Install conscript
  shell: "{{ role_path }}/files/setup_conscript.sh"
  become: yes
  become_user: "{{ user.name }}"
  when: not conscript_installed.stat.exists

- name: Prefetch conscript
  shell: "{{ user.home }}/.conscript/bin/cs --version"
  become: yes
  become_user: "{{ user.name }}"
  when: not conscript_installed.stat.exists
